### ISSUE TITLE
Pinning rule is not unmapped correctly

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Website#101]
### Steps to reproduce

1. Start Website (branch `develop`), WebsiteProvider (branch `develop`), SignIn (branch `develop`)
2. Call `http://localhost:8080/website/resetdata` to load default mappings
3. Go to `http://localhost:8080/signin/generateadminuser` to generate the admin user
4. Go to `http://localhost:8080/website/cms`
5. Sign in as admin user
6. Go to `http://localhost:8080/website/cms/pinningrules`
7. Change the row that says `/signin/user` to `/signin/user2`
8. Press "Save"

### Expected result

The "Sign In" icon should disappear from the top right corner.

### Actual result

The "Sign In" icon does not disappear from the top right corner. This probably means that the pinning rule is not unmapped correctly in WebsiteProvider.

##### Involved apps' version

 - StarcounterApps/Website@d3e2d04bce285cc1bb66b6e820d446a81e301254
 - StarcounterApps/SignIn@8c10b2f1c716bade691a33beee5128cff2a33618
 
##### Browsers affected

- [x] Chrome

### Screenshot

![2017-05-30 15_52_13-website](https://cloud.githubusercontent.com/assets/566463/26586610/feb6734a-454f-11e7-9662-38c6acc468ec.png)

**Comment by warpech** [comment]
@un-tone is this perhaps fixed by PR #111?

**Comment by un-tone** [comment]
Unmapping a rule is not implemented for rules changing, it works only for rules creating/deleting. Sorry that I haven't notified about it explicitly.

**Comment by PatrykSzwer** [comment]
Done in #121. Closing.
