### ISSUE TITLE
Save button does not get enabled for a newly signed in user

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Website#102]
### Steps to reproduce

1. Start Website (branch `develop`), WebsiteProvider (branch `develop`), SignIn (branch `develop`)
2. Call `http://localhost:8080/website/resetdata` to load default mappings
3. Go to `http://localhost:8080/signin/generateadminuser` to generate the admin user
4. Go to `http://localhost:8080/website/cms/surfaces`
5. Sign in as admin user
7. Change the row that says `DefaultTemplate` to `DefaultTemplate2` and click outside of the input

### Expected result

The "Save" button should be changed to active state, allowing you to press it.

### Actual result

The "Save" button does not change the state. It works as expected if you reload the page.

##### Involved apps' version

 - StarcounterApps/Website@d3e2d04bce285cc1bb66b6e820d446a81e301254
 - StarcounterApps/SignIn@8c10b2f1c716bade691a33beee5128cff2a33618
 
##### Browsers affected

- [x] Chrome

### Screenshot

![2017-05-30 15_55_43-website](https://cloud.githubusercontent.com/assets/566463/26586761/74d7d690-4550-11e7-8587-d5447bef0650.png)

**Comment by warpech** [comment]
@bouguila could you please investigate this?

**Comment by warpech** [comment]
@bouguila any luck with this so far?

**Comment by bouguila** [comment]
@warpech i was inspecting thouroughly, but had no success yet.

**Comment by bouguila** [comment]
**Update:** When a user signs in, the RefreshData method (inside CmsSurfacesPage.json.cs) receives a Null Transaction, so the object Trn is set to Null also, thus the property IsDirty gets undefined.

**Comment by warpech** [comment]
Thanks @bouguila for the investigation. Since this app is now owned by @PatrykSzwer, maybe he has some luck in investigating this?

**Comment by PatrykSzwer** [comment]
Fixed in #124. Closing.
