### ISSUE TITLE
Cleanup wrapping

### ISSUE THREAD

**Issue by tomalec** [StarcounterApps/Website#105]
It seems that Website does some magic build on top of the buggy fact we have used `imported-template` on root level https://github.com/StarcounterApps/Website/blob/develop/src/WebsiteProvider/ViewModels/WrapperPage.json.cs#L6-L8
> 
    ///  WrapperPage needs to wrap WebTemplatePage, because Starcounter applies middleware
    ///  from the original request. The default middleware contains &lt;template is="imported-template"&gt;&lt;/template&gt;
    ///  instead of &lt;starcounter-include&gt;, which is why we have to wrap it.

Since https://github.com/Starcounter/level1/pull/4223, that is no longer true

##### Involved apps' version

 - StarcounterApps/Website@162d13c9263ab8e47e0471c1759951445fe0f2c6

**Comment by warpech** [comment]
Implemented in https://github.com/StarcounterApps/Website/pull/107

**Comment by warpech** [comment]
Merged
