### ISSUE TITLE
Implement new UI

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Website#109]
Website becomes a key app but it has a very obsolete UI. I would like to discuss the UI on a meeting at 2017-06-14.

My inspiration for the new UI is Cloudflare's admin panel: 

- https://youtu.be/HsqCB3K9IN8?t=24s
- https://youtu.be/51PXQMDfcFs?t=52s

Of course, in our case the front page does not select domain names but Website surfaces. Everything else happens in context of the selected surface.

**Comment by warpech** [comment]
@PatrykSzwer is working on designing the new UI for the WebsiteEditor. It can be previewed here: https://preview.uxpin.com/5fa3f26d8d1b7794234e9d1cf0f421ffd1f2ec38. To implement this, we will need first to split the view-models to the desired ones (but keep them ugly), then do the HTML, creation of surface groups. It needs to be done by next week, so we can start working on the enhancements.

**Comment by PatrykSzwer** [comment]
Done, closing.
