### ISSUE TITLE
Merge with Launcher

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Website#12]
We are going through planned changes in Launcher (configurability of content zones, themability), which in the end will cause Launcher to have comparable functionality to Website app.

"Launcher" (*Web app*) and "Website" (*Web site*) might become two default themes.

This is a long term goal (few months).

@miyconst WDYT?

**Comment by miyconst** [comment]
I would like to see our Launcher be as flexible as possible, so I am all for it.

**Comment by warpech** [comment]
Before I do this, I will finish some other issues here, because I need a functioning Website app for trying out.

**Comment by warpech** [comment]
This should be merged with Launcher after we are done will all fixes/changes. This will take few weeks.

**Comment by warpech** [comment]
Closing this issue. Launcher was moved to https://github.com/StarcounterAppsFreezer, meaning that it will not be maintained anymore. From now on, all our focus is on Website app.
