### ISSUE TITLE
Support groups of surfaces

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Website#122]
Right now WebsiteEditor/WebsiteProvider support "surfaces" as the topmost concept. Depending on the specificity, surfaces may correspond to real world's:

- web pages
- websites
- fragments of web pages

Problem is that when supporting multiple systems in the same database, there is a need to group related surfaces. For example, I might have few groups of surfaces:

- Website (public)
- Extranet (for customers)
- Backoffice (for employees)

In other case, my system can be used to run dozens of websites:

- Website 1 (consists of 5 surfaces)
- Website 2 (consists of 3 surfaces)
- Website 3 (consists of 4 surfaces)
- Website 4 (consists of 1 surface)
- Admin panel for my surfaces (consists of 3 surfaces)

This clearly shows the need to group surfaces in the UI. Also, a group will have its own identity, allowing to blend additional content from other apps on the group editing level in WebsiteEditor.

How to name this functionality? "Websites", "Surface groups"?

This is a requirement for a customer project.

cc @tomalec, @miyconst, @un-tone, @PatrykSzwer

**Comment by PatrykSzwer** [comment]
Since #138 is done, closing.
