### ISSUE TITLE
Implement Authorization library

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Website#123]
This app needs to implement the Authorization library to allow managing what users have rights to administer surfaces, etc.

**Comment by warpech** [comment]
Reference implementations:

- https://github.com/StarcounterApps/Images
- https://github.com/StarcounterApps/Calendar

@un-tone will add comments to the Images app and then try to write the article for the Cookbook. The article will be similar to https://docs.starcounter.io/guides/web-apps/acceptance-testing-with-selenium/ (btw. that article should be moved to Cookbook).

**Comment by PatrykSzwer** [comment]
Auth library was implemented in #162 . Closing.

**Comment by un-tone** [comment]
Unfortunately it seems like these changes breaks refreshing page after logging in:
![image](https://user-images.githubusercontent.com/1625378/29034603-7d4dcbea-7ba1-11e7-8cf3-146522d4356f.png)
@PatrykSzwer could you please check it?

**Comment by PatrykSzwer** [comment]
I'll check it and create new PR for this.
