### ISSUE TITLE
Change namespaces to be compliant with folder structure

### ISSUE THREAD

**Issue by un-tone** [StarcounterApps/Website#130]
There is a need to change namespaces in the app solution to be compliant with folder structure (except DB classes).
The app becomes bigger and often I see in PRs new classes with incorrect for current approach namespaces. To avoid such fixes I assume it's time to start use the most correct approach of namespace using.

**Comment by warpech** [comment]
This adheres to point 20 in https://starcounter.gitbooks.io/guidelines/content/coding_style/csharp_code_formatting.html

**Comment by PatrykSzwer** [comment]
Closing as done.
