### ISSUE TITLE
Add an example of a responsive surface

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Website#131]
Most of the production surfaces will want to implement Responsive Web Design, which most of the time requires two things:

1. `<meta name="viewport" content="width=device-width, initial-scale=1">`
2. CSS media queries

As http://blog.javierusobiaga.com/stop-using-the-viewport-tag-until-you-know-ho nicely puts it, (1) only makes sense with (2) - and vice versa. We cannot do that on the middleware level, since we don't know if the CSS is responsive. Therefore, a responsive surface needs to include `<meta name="viewport" content="width=device-width, initial-scale=1">`. Lets have a sample surface that shows that.

This was discussed today briefly between me and @malx122

**Comment by PatrykSzwer** [comment]
Done, closing.
