### ISSUE TITLE
Post review for PR #129

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Website#132]
Regarding the line:

```
Handle.GET("/websiteeditor", () => Self.GET("/WebsiteEditor/surfaceGroups"));
```

Please use lowercase URIs: https://starcounter.gitbooks.io/guidelines/content/uris.html

------

Regarding the file `src/WebsiteEditor/wwwroot/WebsiteEditor/css/websiteeditor.css`:

In BEM, there cannot be Element classes like:

```
.website-surface-groups__button
.website-surface-groups__add-button
.website-surface-groups__plus
```

without a Block class `website-surface-groups`.

Better solution is to have two Blocks here:

```
.website-surface-groups-add
.website-surface-groups-add__icon
.website-surface-groups-link
```

**Comment by PatrykSzwer** [comment]
I'll include those changes in next PR which will combine pinning rules with blending points tabs.

**Comment by PatrykSzwer** [comment]
Classes are already changed (and will be change even more in #138). Regarding the URIs in handlers, take a look on commit: 22a9c4ac4c1e11828446e9484dedd44d1ef686f8 
Those will be merged in PR: #138

**Comment by PatrykSzwer** [comment]
Changes are merged, please take a look on them and if everything looks ok, please close this issue. Otherwise I'll create separate PR.

**Comment by warpech** [comment]
Still there are two Elements without Block, but they come from an earlier change:

- `.website-top-menu-item__surface-name`
- `.website-top-menu-item__link`

**Comment by PatrykSzwer** [comment]
I've created PR for that #146

**Comment by PatrykSzwer** [comment]
Final touches done in #146. Closing.
