### ISSUE TITLE
Typos in README.md and CONTRIBUTING.md

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Website#133]
In README.md, there is:

> # Websiteeditor
> Suite of two apps allowing to create surfaces with blending points and attach the result from different applications in the blending points.
>Note: Websiteeditor only wraps responses where the response resource is `Json` (not null) with a session.

Should be:

# WebsiteEditor and WebsiteProvider
Suite of two apps allowing to create surfaces with blending points and attach the result from different applications in the blending points.

Note: WebsiteProvider ignores responses other than of type `Json` with a session.

-----

In CONTRIBUTING.md, `Websiteeditor.sln` should be changed to `Website.sln`.

-----

WebsiteEditor should be always written as "WebsiteEditor" or "websiteeditor", never "Websiteeditor".

**Comment by PatrykSzwer** [comment]
PR for that: #148

**Comment by PatrykSzwer** [comment]
Done, closing.
