### ISSUE TITLE
Implement new UI for catching rules

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Website#150]
<img width="726" alt="screen shot 2017-07-27 at 16 40 32" src="https://user-images.githubusercontent.com/566463/28676203-551ca8e0-72ea-11e7-9950-7ef7502876e7.png">

> If a rule is nestable, other surfaces will be matched against this surface's View URI. It results in this surface being pinned in the default blending point of another surface that catches it. 
> Note: currently only rules with specified URI are nestable.

**Comment by PatrykSzwer** [comment]
Done in #159 . Closing.
