### ISSUE TITLE
Error when running Launchpad after Website

### ISSUE THREAD

**Issue by Mihaiii** [StarcounterApps/Website#156]
This might make sense from the developer's point of view, but it won't make sense for the end user.
Feel free to close if it's not an "issue" (whoever you are).

### Steps to reproduce
1. Run https://github.com/StarcounterApps/Website/commit/f2a974a9ce1029e9efb40121970704778cfbdd82 (current latest version on `develop`)
2. Run https://github.com/StarcounterApps/Launchpad/commit/e9345f42bc0431daf2eef27ac4e98e79114cc988 (current latest version on `develop`)
3. Go to `http://localhost:8080/launchpad` (or also run https://github.com/StarcounterApps/SampleWebsiteTheme/commit/fa14b9b359ad6a945434d1f913930d94a45cc83d before Launchpad, go to `http://localhost:8080/websiteeditor` and try to see what apps are running)

SC version: 2.3.1.6860

<img width="935" alt="launchpad" src="https://user-images.githubusercontent.com/8951553/28806055-2ba48f00-766e-11e7-818c-6de43ff266be.png">

>  System.NullReferenceException: Object reference not set to an instance of an object.
>     at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\BuildAgent\work\sc-6711\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 169
>     at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\BuildAgent\work\sc-6711\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
>     at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\BuildAgent\work\sc-6711\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 763
>  HResult=-2147467261
> 
> More information about this error may be available in the server error log.

<img width="356" alt="errwebsitelaunchpad" src="https://user-images.githubusercontent.com/8951553/28806642-74115022-7671-11e7-80c2-faa151e096af.png">

**Comment by un-tone** [comment]
It is hard to understand what is happening when looking from applications level.
@alemoi could you please take a look on this issue?

**Comment by Mihaiii** [comment]
Afaik when an apps starts, every other app that was already running restrats and I guess there's a specific order.

There used to be https://github.com/StarcounterAppsFreezer/Launcher , but now it's deprecated. Launchpad app took it's place.

**Comment by un-tone** [comment]
As I know for Launcher order of apps starting does not affect

**Comment by Mihaiii** [comment]
Hmm, just tested it now and it seems that not the case (anymore?).
My bad.

**Comment by un-tone** [comment]
Currently I can't reproduce this bug.
@Mihaiii could you please check this bug with last versions of apps from `develop` in last RC SC build 2.3.1.6903

**Comment by Mihaiii** [comment]
I can't reproduce it either.

Closing as no longer reproducible on latest RC.

**Comment by un-tone** [comment]
The issue has appeared again and will be fixed in #192
