### ISSUE TITLE
Wrong generated catching rule

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Website#163]
What is 

```
/websiteprovider/surfaces
```

Should be:

```
/websiteeditor/surfacegroups
```

in https://github.com/StarcounterApps/Website/blob/develop/src/WebsiteEditor/Helpers/DataHelper.cs#L107

----

I assume that `/websiteprovider/help?topic=surfaces` in that file should also be changed to `websiteeditor`.

**Comment by PatrykSzwer** [comment]
Created PR for that: #165

**Comment by PatrykSzwer** [comment]
Closing as done.
