### ISSUE TITLE
Surfaces generated in SampleWebsiteTheme don't show up

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Website#164]
### Steps to reproduce

1. Start WebsiteEditor, WebsiteProvider and SignIn from `develop` branch.
2. Go to `http://localhost:8080/websiteeditor/resetdata` to reset WebsiteEditor data.
3. Start SampleWebsiteTheme
4. Go to `http://localhost:8080/WebsiteEditor`

### Expected result

The surfaces from SampleWebsiteTheme should show up on the surface groups page in WebsiteEditor.

### Actual result

They show up in Starcounter Administrator but not in WebsiteEditor.

### Screenshot

![2017-08-04 18_53_24-websiteeditor](https://user-images.githubusercontent.com/566463/28978500-8144bb80-7946-11e7-8cba-36db1a470177.png)

![2017-08-04 18_53_36-starcounter administrator](https://user-images.githubusercontent.com/566463/28978503-859f13b0-7946-11e7-82a9-e10fb6c7a052.png)

**Comment by PatrykSzwer** [comment]
It's more a SampleWebsiteTheme issue, since It's not assigning surface group to new surfaces, but I'll fix it in website anyway. We were discussing with @un-tone about correctness of solution where unassigned group is still a group, not meant by empty entry there. This issue proves that we need to change it on that way.

**Comment by PatrykSzwer** [comment]
Created PR related to this: #166.

**Comment by warpech** [comment]
That's a general pitfall with Starcounter Apps that use a shared data model - you cannot be sure that the data model is used like you intended.

RDBMS have the same problem - there might be many apps using the same db tables and it is not granted that all of the apps will follow exactly the same conventions. If it is possible to create incomplete relations, you have to live with incomplete relations.

**Comment by PatrykSzwer** [comment]
Yes, that issue showed me exactly that in a practice way.

**Comment by PatrykSzwer** [comment]
Done in #166. Closing.
