### ISSUE TITLE
Paper-collapse-item is installed at wrong path

### ISSUE THREAD

**Issue by tomalec** [StarcounterApps/Website#170]
### Steps to reproduce

Go to https://github.com/StarcounterApps/Website/tree/develop/src/WebsiteEditor/wwwroot

### Expected result
It should contain app own static files, and `/sys` folder with dependencies.

### Actual result
There is also 
`paper-collapse-item`

##### Involved apps' version

 - StarcounterSamples/Website@b150930c0b40ad3fcb378a0ca030e7ec9048fe90
 
##### Browsers affected
n/a

**Comment by PatrykSzwer** [comment]
Closing as done.
