### ISSUE TITLE
Getting "Can not find referenced Html file" error

### ISSUE THREAD

**Issue by un-tone** [StarcounterApps/Website#177]
### Steps to reproduce

1. Run **WebsiteEditor** and **WebsiteProvider** apps from `develop` branch
1. Run **SignIn** app from `develop` branch
1. If user is not created go to <http://localhost:8080/signin/generateadminuser>
1. Go to <http://localhost:8080/signin/signinuser> and log in
1. Go to <http://localhost:8080/websiteeditor>

### Expected result

The requested page is loaded.

### Actual result

Get the error:
```
System.ArgumentOutOfRangeException: Заданный аргумент находится вне диапазона допустимых значений.
Имя параметра: Can not find referenced Html file: "/websiteprovider/surfaces/DefaultSurface.html"
   в Starcounter.HtmlFromJsonProvider.ProvideFromFilePath[T](String filePath) в C:\TeamCity\BuildAgent\work\sc-7269\Level1\src\Starcounter\Middleware\HtmlFromJsonProvider.cs:строка 58
   в Starcounter.HtmlFromJsonProvider.Invoke(MimeProviderContext context, Action next) в C:\TeamCity\BuildAgent\work\sc-7269\Level1\src\Starcounter\Middleware\HtmlFromJsonProvider.cs:строка 52
   в Starcounter.MimeProviderMap.InvokeAll(MimeType type, Request request, IResource resource) в C:\TeamCity\BuildAgent\work\sc-7269\Level1\src\Starcounter\Middleware\MimeProviderMap.cs:строка 126
   в Starcounter.Internal.ResourceMimeConverter.TryConvert(Request request, IResource resource, String mimeTypeStr, String& resultingMimeType) в C:\TeamCity\BuildAgent\work\sc-7269\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\ResourceMimeConverter.cs:строка 56
   в Starcounter.Internal.ResourceMimeConverter.Convert(Request request, Response response, String& resultingMimeType) в C:\TeamCity\BuildAgent\work\sc-7269\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\ResourceMimeConverter.cs:строка 46
   в Starcounter.Response.ConvertResource(Request req) в C:\TeamCity\BuildAgent\work\sc-7269\Level1\src\Starcounter.Internal\Http\Response.cs:строка 765
   в Starcounter.Response.ConstructFromFields(Request req, Byte[] givenBuffer) в C:\TeamCity\BuildAgent\work\sc-7269\Level1\src\Starcounter.Internal\Http\Response.cs:строка 821
   в Starcounter.Request.SendResponse(Response resp, Byte[] serializationBuf) в C:\TeamCity\BuildAgent\work\sc-7269\Level1\src\Starcounter.Internal\Http\Request.cs:строка 1243
   в Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) в C:\TeamCity\BuildAgent\work\sc-7269\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:строка 819
ParamName=Can not find referenced Html file: "/websiteprovider/surfaces/DefaultSurface.html"
HResult=-2146233086

More information about this error may be available in the server error log.
```

##### Involved apps' version

 - ac1b85133e67f8da187cb2767d83d59272e4d2f6
 - https://github.com/StarcounterApps/SignIn/commit/a46d297a1393b64a2002e8c9ed8da177c6a748a4

### Screenshot

![image](https://user-images.githubusercontent.com/1625378/29323494-bc9c9ec2-81e9-11e7-9331-40490ae1f01d.png)

**Comment by un-tone** [comment]
The issue is in calling of the following code from `HtmlFromJsonProvider.ProvideFromFilePath<T>` method:
```csharp
Self.GET<byte[]>("/websiteprovider/surfaces/DefaultSurface.html")
```
There is important moment, that when you at first time go to `http://localhost:8080/signin/signinuser` the `Self.GET` calling works well. But for some reason it returns `null` when you go to `http://localhost:8080/WebsiteEditor`.
In some undetermined cases it works in opposite: you go to `http://localhost:8080/WebsiteEditor` and it works well but when you go to `http://localhost:8080/signin/signinuser` it throws the error.

It is problematically to investigate the issue from the apps' level further, I think it should be done from the platform's level. @chrhol could you please take a look at this?

**Comment by chrhol** [comment]
I have a couple of other tasks I need to finish first and a planning meeting later today. I hope to have time today, but in worst case I wont have time to look at this and the other website issue until after the weekend.

**Comment by chrhol** [comment]
Found the cause I think. A fix is pushed and will be included in the next nightly build.

**Comment by un-tone** [comment]
The issue is fixed. Thanks @chrhol!

**Comment by un-tone** [comment]
Closing the issue as fixed.
Be aware that #176 and #161 are related to this issue.
