### ISSUE TITLE
Starting apps before WebsiteProvider cause a exception

### ISSUE THREAD

**Issue by threezool** [StarcounterApps/Website#180]
### Steps to reproduce
Start the apps from AutoAuditSuite Repo (Use dev-bransch but exclude the CreditSafe Project) from Visual Studio and let dem boot up, add SignIn, LaunchPad and WebsiteEditor. All should work fine upp untill now.

Then add the WebsiteProvider and a exception will occure.

If i instead reverse the order and star all the other apps and then the apps from AutoAuditSuite last it boots up as it should.

### Expected result
WebsiteProvider should start and handle requests.

### Actual result
It craches with the exception: System.Exception: 'Surface is not defined for the Pinning Rule!'

### Technical information
The exception originates when the main handlers are registered but i have not gone deeper since i got it to work by reversing boot order.

##### Starcounter version
**Starcounter-RC-2.3.1.7018**

**Comment by PatrykSzwer** [comment]
I've tried to reproduce this with newest versions of develop branches and SC version 2.3.1.7034. No results, seems unreproducable. If You manage to reproduce it still, please provide more detailed steps to do it. If not, please close the issue.

**Comment by threezool** [comment]
Looks like the issue has been solved in the last SC version, closing.
