### ISSUE TITLE
No refresh during switching between tabs of surface.

### ISSUE THREAD

**Issue by PatrykSzwer** [StarcounterApps/Website#186]
Issue created for bug mentioned here: https://github.com/StarcounterApps/Website/issues/176#issuecomment-327110473

### Steps to reproduce
1. Go to SidebarSurface page.
2. When General view is loaded click on Catching rules on navigation bar.
### Expected result
View is redirected to catching rules partial page.
### Actual result
URL is changed but nothing more is happening.
##### Starcounter version 2.3.1.7138

**Comment by PatrykSzwer** [comment]
As part of investigating this, I've tried to replace links in navigation bar to triggers with puppet-redirect, but without results.

**Comment by un-tone** [comment]
@PatrykSzwer thanks for the help. But I've already fixed the issue in `fix-nested-surface-render` branch 😄. Currently I'm working on tests for nested surfaces.

**Comment by PatrykSzwer** [comment]
Ou sorry, but there is not any annotation to this branch so I though It's still unresolved. That's great!

**Comment by un-tone** [comment]
Closing as fixed.

**Comment by un-tone** [comment]
Reopening due to #202

**Comment by un-tone** [comment]
Actually #205 and #206 fix the issue. Please review these PRs.

**Comment by un-tone** [comment]
Fixed. Closing...
