### ISSUE TITLE
WebsiteProvider causes System.NullReferenceException when running with Launchpad

### ISSUE THREAD

**Issue by bouguila** [StarcounterApps/Website#192]
### Steps to reproduce
1. Checkout Launchpad and Website both from develop branch
2. Build and run both apps
3. Go to localhost:8080/Launchpad

### Actual result
System.NullReferenceException: Object reference not set to an instance of an object.
   at Starcounter.XSON.SiblingList.CompareAndInvalidate(SiblingList previousSiblings) in C:\TeamCity\BuildAgent\work\sc-8192\Level1\src\Starcounter.XSON\Class Json\SiblingList.cs:line 245
   at Starcounter.Internal.JsonResponseMerger.DoMerge(Request req, Response resp, List`1 responses) in C:\TeamCity\BuildAgent\work\sc-8192\Level1\src\Starcounter\Apps\JsonResponseMerger.cs:line 65
   at Starcounter.Internal.JsonResponseMerger.DefaultMerger(Request req, Response resp, List`1 responses) in C:\TeamCity\BuildAgent\work\sc-8192\Level1\src\Starcounter\Apps\JsonResponseMerger.cs:line 41
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\BuildAgent\work\sc-8192\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 398
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\BuildAgent\work\sc-8192\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 96
   at Starcounter.Rest.UriManagedHandlersCodegen.RunUriMatcherAndCallHandler(String methodSpaceUriSpace, String methodSpaceUriSpaceLower, Request req, UInt16 portNumber, Response& resp) in C:\TeamCity\BuildAgent\work\sc-8192\Level1\src\Starcounter.Rest\UriManagedHandlersCodegen.cs:line 1232

**Comment by bouguila** [comment]
ping @un-tone @PatrykSzwer

**Comment by PatrykSzwer** [comment]
I've tried to reproduce with dev branches of website and launchpad and with SC version 2.3.1.7158, without results. I'll try with higher version of SC also.

**Comment by un-tone** [comment]
I can't reproduce it too with SC 2.3.1.7166.
@bouguila can you provide more detailed steps with apps running on clean DB?

**Comment by PatrykSzwer** [comment]
I've also tried to reproduce this also on SC 2.3.1.7166, with and without SignIn app running, still no reproduction.

**Comment by bouguila** [comment]
thank you for the investigation guys, i will check the steps to reproduce that.
Anyway the error is still http://inside.starcounter.com since WebsiteProvider is running

**Comment by PatrykSzwer** [comment]
What error do You mean? For me on inside website works fine.

**Comment by bouguila** [comment]
update: a Wesiteeditor/resetdata solved the problem.

**Comment by PatrykSzwer** [comment]
Great! I'll close this issue, as not reproducible anymore.

**Comment by bouguila** [comment]
the problem is again there, and we cannot just do a resetdata everytime. @PatrykSzwer  Could you please go to inside.starcounter.com to see the error?
cc @un-tone

**Comment by PatrykSzwer** [comment]
Do You know how to reproduce this problem locally?

**Comment by bouguila** [comment]
i am able to reproduce it just following the steps above

**Comment by PatrykSzwer** [comment]
But the problem occurred after some time so there had to be some specific actions to make error in DB. Do You know what did You did on inside before It stopped worked again?

**Comment by bouguila** [comment]
actually i did nothing apart from changing some compositions

**Comment by un-tone** [comment]
1. Does it help if you restart all the running apps?
2. Please provide the order of starting apps

**Comment by bouguila** [comment]
@un-tone 
1. the restart doesn't help
2. the order does not matter

**Comment by un-tone** [comment]
I see that on `inside` not only Launchpad and Website are running. Please provide the full list.

**Comment by un-tone** [comment]
@bouguila maybe you can provide me a dump from `inside`?

**Comment by PatrykSzwer** [comment]
@un-tone, here is the list of running apps on inside:
![image](https://user-images.githubusercontent.com/25042256/30364239-aab26706-9863-11e7-9ae4-3bea8074e72a.png)
I will also provide You dump from DB.

**Comment by un-tone** [comment]
There was the same issue https://github.com/StarcounterApps/Website/issues/156

**Comment by un-tone** [comment]
I found the way to reproduce the bug. You just need to add a pining rule with `/Launchpad` URI. I'll describe it more detailed below.

**Comment by un-tone** [comment]
### Steps to reproduce

1. Run **WebsiteEditor** and **WebsiteProvider** apps from `develop` branch.
1. Run **SignIn** app from `develop` branch.
1. Run **Launchpad** app from `develop` branch.
1. If user is not created go to <http://localhost:8080/signin/createadminuser>.
1. Go to <http://localhost:8080/signin/signinuser> and log in.
1. Go to <http://localhost:8080/websiteeditor>.
1. Select "DefaultSurface" and go to "Blending points" tab.
1. Expand "TopBar" item and create a new pinning rule with `/Launchpad` Pin URI.
1. Go to <http://localhost:8080/Launchpad>.

### Expected result

The requested page is loaded.

### Actual result

Get the error:

```
System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в Starcounter.XSON.SiblingList.CompareAndInvalidate(SiblingList previousSiblings) в C:\TeamCity\BuildAgent\work\sc-8192\Level1\src\Starcounter.XSON\Class Json\SiblingList.cs:строка 245
   в Starcounter.Internal.JsonResponseMerger.DoMerge(Request req, Response resp, List`1 responses) в C:\TeamCity\BuildAgent\work\sc-8192\Level1\src\Starcounter\Apps\JsonResponseMerger.cs:строка 65
   в Starcounter.Internal.JsonResponseMerger.DefaultMerger(Request req, Response resp, List`1 responses) в C:\TeamCity\BuildAgent\work\sc-8192\Level1\src\Starcounter\Apps\JsonResponseMerger.cs:строка 41
   в Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) в C:\TeamCity\BuildAgent\work\sc-8192\Level1\src\Starcounter.Rest\UriHandlersManager.cs:строка 398
   в Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) в C:\TeamCity\BuildAgent\work\sc-8192\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:строка 96
   в Starcounter.Rest.UriManagedHandlersCodegen.RunUriMatcherAndCallHandler(String methodSpaceUriSpace, String methodSpaceUriSpaceLower, Request req, UInt16 portNumber, Response& resp) в C:\TeamCity\BuildAgent\work\sc-8192\Level1\src\Starcounter.Rest\UriManagedHandlersCodegen.cs:строка 1232
   в Starcounter.Self.DoSelfCall(UInt16 portNumber, String method, String relativeUri, Dictionary`2 headersDictionary, String body, Byte[] bodyBytes, HandlerOptions handlerOptions, Request req) в C:\TeamCity\BuildAgent\work\sc-8192\Level1\src\Starcounter.Internal\Rest\Self.cs:строка 390
   в Starcounter.Self.GET(UInt16 port, String uri, Dictionary`2 headersDictionary, HandlerOptions ho) в C:\TeamCity\BuildAgent\work\sc-8192\Level1\src\Starcounter.Internal\Rest\Self.cs:строка 133
   в Starcounter.Rest.UserHandlerInfo.<>c__DisplayClass18_0.<RunUserDelegate>b__0() в C:\TeamCity\BuildAgent\work\sc-8192\Level1\src\Starcounter.Rest\UriHandlersManager.cs:строка 346
   в Starcounter.Internal.StarcounterEnvironment.RunWithinApplicationInternal(String desiredAppName, Action action) в C:\TeamCity\BuildAgent\work\sc-8192\Level1\src\Starcounter.Internal\Mock\StarcounterEnvironment.cs:строка 142
   в Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) в C:\TeamCity\BuildAgent\work\sc-8192\Level1\src\Starcounter.Rest\UriHandlersManager.cs:строка 345
   в Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) в C:\TeamCity\BuildAgent\work\sc-8192\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:строка 96
   в Starcounter.Rest.UriManagedHandlersCodegen.RunUriMatcherAndCallHandler(String methodSpaceUriSpace, String methodSpaceUriSpaceLower, Request req, UInt16 portNumber, Response& resp) в C:\TeamCity\BuildAgent\work\sc-8192\Level1\src\Starcounter.Rest\UriManagedHandlersCodegen.cs:строка 1232
   в Starcounter.Self.DoSelfCall(UInt16 portNumber, String method, String relativeUri, Dictionary`2 headersDictionary, String body, Byte[] bodyBytes, HandlerOptions handlerOptions, Request req) в C:\TeamCity\BuildAgent\work\sc-8192\Level1\src\Starcounter.Internal\Rest\Self.cs:строка 390
   в Starcounter.Self.GET(String uri, Func`1 substituteHandler) в C:\TeamCity\BuildAgent\work\sc-8192\Level1\src\Starcounter.Internal\Rest\Self.cs:строка 90
   в Starcounter.Self.GET[T](String uri, Func`1 substituteHandler) в C:\TeamCity\BuildAgent\work\sc-8192\Level1\src\Starcounter.Internal\Rest\Self.cs:строка 48
   в WebsiteProvider.Api.ContentHandlers.UpdateTemplateSections(String requestUri, Response response, SurfacePage content, WebUrl url) в C:\Users\untone\Documents\Projects\Starcounter\Git\StarcounterApps\Website\src\WebsiteProvider\Api\ContentHandlers.cs:строка 157
   в WebsiteProvider.Api.ContentHandlers.<Register>b__9_1(String requestUri, String responseKey, String requestKey) в C:\Users\untone\Documents\Projects\Starcounter\Git\StarcounterApps\Website\src\WebsiteProvider\Api\ContentHandlers.cs:строка 70
   в lambda_method(Closure , Request , IntPtr , IntPtr )
   в Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) в C:\TeamCity\BuildAgent\work\sc-8192\Level1\src\Starcounter.Rest\UriHandlersManager.cs:строка 231
   в Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) в C:\TeamCity\BuildAgent\work\sc-8192\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:строка 96
   в Starcounter.Rest.UriManagedHandlersCodegen.RunUriMatcherAndCallHandler(String methodSpaceUriSpace, String methodSpaceUriSpaceLower, Request req, UInt16 portNumber, Response& resp) в C:\TeamCity\BuildAgent\work\sc-8192\Level1\src\Starcounter.Rest\UriManagedHandlersCodegen.cs:строка 1232
   в Starcounter.Self.DoSelfCall(UInt16 portNumber, String method, String relativeUri, Dictionary`2 headersDictionary, String body, Byte[] bodyBytes, HandlerOptions handlerOptions, Request req) в C:\TeamCity\BuildAgent\work\sc-8192\Level1\src\Starcounter.Internal\Rest\Self.cs:строка 390
   в Starcounter.Self.GET(String uri) в C:\TeamCity\BuildAgent\work\sc-8192\Level1\src\Starcounter.Internal\Rest\Self.cs:строка 74
   в WebsiteProvider.Api.ContentHandlers.<RegisterFilter>b__10_1(Request request, Response response) в C:\Users\untone\Documents\Projects\Starcounter\Git\StarcounterApps\Website\src\WebsiteProvider\Api\ContentHandlers.cs:строка 112
   в Starcounter.Handle.RunResponseFilters(Request req, Response resp) в C:\TeamCity\BuildAgent\work\sc-8192\Level1\src\Starcounter.Internal\Handle.cs:строка 539
   в Starcounter.Request.SendResponse(Response resp, Byte[] serializationBuf) в C:\TeamCity\BuildAgent\work\sc-8192\Level1\src\Starcounter.Internal\Http\Request.cs:строка 1213
   в Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) в C:\TeamCity\BuildAgent\work\sc-8192\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:строка 819
HResult=-2147467261

More information about this error may be available in the server error log.
```

### Notes

This happens because WebsiteProvider tries to combine two instances (the original one and from pinning content) of the same `/Launchpad` page into one JSON and the app changes parent of the original JSON here https://github.com/StarcounterApps/Website/blob/develop/src/WebsiteProvider/Api/ContentHandlers.cs#L160. The issue can be eliminated if I replace `(json.Parent ?? new ContentWrapperPage {Content = json})` with just original `json`. But I can't do it in this way because it entails the other "blending already blended URIs" issue.

-----

@chrhol can you please take a look at this issue or give me some clues which helps me to find a way fixing it?

**Comment by chrhol** [comment]
Looks like it was a bug in Starcounter. I've just pushed a fix for it, should be included in the next nightly version.

**Comment by bouguila** [comment]
@chrhol i've upgraded SC to today's version and the problem is gone! Thanks

**Comment by bouguila** [comment]
Closing as fixed.

**Comment by un-tone** [comment]
Great! Thank you, @chrhol
