### ISSUE TITLE
Rename "Catching rules" to "Routing", add more info

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Website#193]
In order to make catching rules clearer, let's rename it and add more information about how to use it - right in the app.

1. Rename Catch URIs to Routing
2. If there are no routes for a Surface, add a warning: "This surface has no routes. Click here to add a catch all route.
3. Rename "Nestable" checkbox to "Disallow route nesting"
4. Add a sidebar on the Routing page with the following help information. Please propose any changes that make it more understandable.

-----
 
## Routing order
 
Routing in Website runs in the order from top to bottom. 
 
## Route matching
 
The first route matching the input URI is applied. In result, the response to that URI is injected in the "default" blending point of the routed surface. The other routes are ignored. (but - see Route nesting).
 
## Route wildcards
 
Wildcard parameters (`{?}`) are accepted as part of the input URI.
 
## Route nesting
 
After a route was successfully matched, the routing engine re-runs from the start. It takes the `view URI` of the matched surface as the input URI. This allows to wrap surfaces in other surfaces.
 
If you want to break from nesting of the route, check "Disallow route nesting"

**Comment by warpech** [comment]
I was wrong about the label "Disallow route nesting". Many UX resources teach that labels of checkboxes should always be positive. For example: https://uxplanet.org/checkbox-and-toggle-in-forms-f0de6086ac41

Can we go with "Allow route nesting" instead?

Sorry for this.

**Comment by PatrykSzwer** [comment]
Sure, no problem.

**Comment by PatrykSzwer** [comment]
Closing as done.
