### ISSUE TITLE
Remove <br> from HTML templates

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Website#207]
As reported by @tomalec in https://github.com/StarcounterApps/Website/pull/172, we need to replace the usage of `<br>` in `SurfaceGroupsPage.html` with CSS.

The problem with `<br>` is that if you have them, you should add slot attributes to them. Having more slots just to get a new line is an overhead, obviously. Hence, better to do that with CSS.

**Comment by PatrykSzwer** [comment]
Closing as done.
