### ISSUE TITLE
Get rid of Key and ObjectID properties using

### ISSUE THREAD

**Issue by un-tone** [StarcounterApps/Website#216]
In according to this issue https://github.com/Starcounter/Home/issues/252 and decisions from https://github.com/Starcounter/level1/issues/4210 we should replace all occurrences of using `Key` and `ObjectID` properties with `ObjectNo`.

**Comment by warpech** [comment]
Even better, replace it with `DbHelper.FromID(DbHelper.Base64DecodeObjectID(id))` and pass objects in queries instead of ids.

**Comment by un-tone** [comment]
Closing as done.
