### ISSUE TITLE
Default surface from template is created without blending points

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Website#222]
### Steps to reproduce

1. Start WebsiteEditor (branch `develop`), SignIn (branch `develop`)
2. Call `http://localhost:8080/website/resetdata` to load default mappings
3. Go to `http://localhost:8080/signin/signinuser` to generate the admin user and sign in
4. Go to `http://localhost:8080/websiteeditor/surfacegroups`
5. Create a new surface from the "Default" template
6. Click on "New default template" -> "Blending points"

### Expected result

The new surface should have two blending points with the bottom one marked as `default`. 

### Actual result

The new surface has no blending points.

##### Starcounter version 2.3.1.7294

**Comment by PatrykSzwer** [comment]
Closing as done.
