### ISSUE TITLE
SurfaceGroupsPage is not DRY

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Website#227]
The code in `SurfaceGroupsPage.html`, `json` and `json.cs` is duplicated for grouped and ungrouped surfaces in lines:

- https://github.com/StarcounterApps/Website/blob/develop/src/WebsiteEditor/wwwroot/WebsiteEditor/viewmodels/SurfaceGroupsPage.html#L9-L56
- https://github.com/StarcounterApps/Website/blob/develop/src/WebsiteEditor/wwwroot/WebsiteEditor/viewmodels/SurfaceGroupsPage.html#L60-L108

Ungrouped surfaces should be seen as belonging to a group that is null. There is no need for the code to be duplicated.

**Comment by un-tone** [comment]
Closing as done.
