### ISSUE TITLE
Adapt view to Declarative Shadow DOM

### ISSUE THREAD

**Issue by Mackiovello** [StarcounterApps/Website#42]
According to https://github.com/Starcounter/RebelsLounge/issues/59

Follow the guidelines in the following three posts to adapt the views to use Declarative Shadow DOM:

* [Layout compositions for HTML partials](https://starcounter.io/layout-compositions-html-partials/)
* [How to Apply New Shadow DOM Layouts to Existing HTML Templates](https://starcounter.io/making-apps-blendable/)
* [HTML View Guidelines](https://docs.starcounter.io/guides/puppet-web-apps/html-view-guidelines/)

**Comment by tomalec** [comment]
Implemented with https://github.com/StarcounterApps/Website/issues/80
