### ISSUE TITLE
DenyPage.html and CmsPage.html does not need `dom-bind`

### ISSUE THREAD

**Issue by tomalec** [StarcounterApps/Website#45]
Pages
- https://github.com/StarcounterPrefabs/Website/blob/master/src/Website/wwwroot/Website/viewmodels/DenyPage.html
- https://github.com/StarcounterPrefabs/Website/blob/master/src/Website/wwwroot/Website/viewmodels/CmsPage.html
Does not need `<template is="dom-bind">`. I suggest to remove it to improve performance and code clarity.

**Comment by warpech** [comment]
@un-tone can you pls take it?

**Comment by un-tone** [comment]
Created PR https://github.com/StarcounterApps/Website/pull/84

**Comment by un-tone** [comment]
Closing as done.
