### ISSUE TITLE
Navigation through page causes double replace operation

### ISSUE THREAD

**Issue by tomalec** [StarcounterApps/Website#46]
### Steps to reproduce
1. Run Website + SignIn + People
2. Go to `http://localhost:8080/people`
3. Navigate using People menu back ant forth
4. Check Network tab

### Expected result
`http://localhost:8080/people/persons` XHR Should contain only one `replace` for `/WebTemplatePage/Sections/Main/Rows/0`.

### Actual result
Two are send:
```js
[
//...
{
    "op": "replace",
    "path": "/WebTemplatePage/Sections/Main/Rows/0",
    "value": {
        "WebsiteProvider": {
            "Html": "",
            "WebTemplatePage": {
                "Html": "",
                "Name": "",
                "Sections": {}
            }
        },
        "People": {
            "Html": "/People/viewmodels/StandalonePage.html",
            "ShowMenu": true,
            "CurrentPage": {}
        }
    }
}, {
    "op": "replace",
    "path": "/WebTemplatePage/Sections/Main/Rows/0",
    "value": {
        "WebsiteProvider": {
            "Html": "",
            "WebTemplatePage": {
                "Html": "",
                "Name": "",
                "Sections": {}
            }
        },
        "People": {
            "Html": "/People/viewmodels/StandalonePage.html",
            "ShowMenu": true,
            "CurrentPage": {}
        }
    }
},
//...
]
```

### Technical information

That may cause us performance, time, FOUC and weird issues like https://github.com/Juicy/imported-template/issues/26#issuecomment-282296551

##### Involved apps' version

 - https://github.com/StarcounterSamples/People/commit/d6469f7627a49a8319662f0da6c5493511e2d7c5
 - https://github.com/StarcounterPrefabs/SignIn/commit/4bf03aac97c2eb411f1ba43bd59da3855eeb9230
- https://github.com/StarcounterPrefabs/Website/commit/8633a0cb821c5dbee341b18b5f1e2ba0d3bcba7a
 
##### Browsers affected
n/a

//cc @warpech

**Comment by warpech** [comment]
@un-tone can you please investigate this?

**Comment by un-tone** [comment]
Create PR https://github.com/StarcounterPrefabs/Website/pull/52

**Comment by warpech** [comment]
@chrhol the PR #52 fixes this problem. For me this looks like a bug in Starcounter. Could you confirm, and if yes, then create a Starcounter issue?

**Comment by un-tone** [comment]
Closing as done.
