### ISSUE TITLE
Allow more catching rules than just URI

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Website#48]
For the beginning, it should be possible to use not just URI for a rule but also a regexp matched against one or more HTTP headers (`User-Agent`, `Cookie`, etc).

CloudFlare has a nice UI for that. Check out the video: https://www.cloudflare.com/features-page-rules/

@un-tone WDYT about that?

**Comment by un-tone** [comment]
@warpech looks nice

**Comment by warpech** [comment]
We need the following kinds of the catching rules: 

- URI path matches (this one already exists). Intended for the `path` fragment of the URI that starts after the domain name
- HTTP header matches. Intended for matching the value of such HTTP headers as: `host`, `user-agent`, etc

The rules specified for a single surface should be treaded as "AND" rules (not "OR").

**Comment by warpech** [comment]
@bouguila could you please work on this? Recommended reviewer: @un-tone

**Comment by un-tone** [comment]
Created PRs https://github.com/StarcounterApps/Website/pull/136 and https://github.com/StarcounterApps/Simplified/pull/62

**Comment by un-tone** [comment]
Closing as done
