### ISSUE TITLE
Moving between pages reloads the whole blending point

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Website#50]
@un-tone could you please investigate?

### Steps to reproduce

1. Start People (branch `develop`), Website (branch `develop`), WebsiteProvider (branch `develop`), SignIn (branch `develop`)
2. Call `http://localhost:8080/website/resetdata` to load default mappings
3. Go to `http://localhost:8080/signin/generateadminuser` to generate the admin use
4. Go to `http://localhost:8080/people`
5. Sign in as admin user
6. Reload the page
7. Now, press the "People" link in the top menu
8. Then, press the "Organisations" link in the top menu

### Expected result

Since the "People" page and the "Organisations" page are the same `CurrentPage` inside People's `MasterPage`, switching between these pages should not cause the top bar menu to refresh.

### Actual result

Switching between "People" and "Organisations" causes the whole `MasterPage` to reload, which results in the "font growing animation" every time you click a button in the top menu.

Also, the menu gets stamped out again at the bottom of the page, but that is another problem (https://github.com/Juicy/imported-template/issues/26)

##### Browsers affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Screenshot

![bug](https://cloud.githubusercontent.com/assets/566463/23550526/a982f62e-0011-11e7-9db3-451334aab1a9.gif)

**Comment by un-tone** [comment]
Created PR https://github.com/StarcounterPrefabs/Website/pull/53

**Comment by un-tone** [comment]
The issue "the menu gets stamped out again at the bottom of the page" (https://github.com/Juicy/imported-template/issues/26) is fixed with this PR https://github.com/StarcounterPrefabs/Website/pull/53

**Comment by un-tone** [comment]
Added another related issue https://github.com/StarcounterApps/Website/issues/55

**Comment by un-tone** [comment]
Closing as done.
