### ISSUE TITLE
Support regex in Catch Uris

### ISSUE THREAD

**Issue by joozek78** [StarcounterApps/Website#54]
Outline
---

You want to assign a layout to whole app, but you don't know the exact URLs of this app. There is a real scenario (Sweoffshore) where you create a layout for a suite that might expand in the future and you can't predict exact URLs in those apps . Catch Uris only support wildcards for one segment, so `/App/{?}` would catch `/App/abc`, but wouldn't catch `/App/a/b/c`.

Workaround
---

Create a bunch of Catch Uris: `/App/{?}`, `/App/{?}/{?}`, and so on. The downside is that you can't refer whole group of them when creating Pinning Rule.

Proposed solution
---

Support regular expressions, not just "{?}" wildcard. That way you can cover arbitrary set of URLs

Anticipated problems
---

Conflicting rules. Those conflicts could be resolved by adding "order" field or by some logic based on specificity (like CSS does)

**Comment by un-tone** [comment]
Closing as done
