### ISSUE TITLE
Moving to a page with not final Catching rule reloads whole Surface

### ISSUE THREAD

**Issue by un-tone** [StarcounterApps/Website#55]
### Steps to reproduce

1. Start Website (branch `develop`), WebsiteProvider (branch `develop`), SignIn (branch `develop`)
2. Call `http://localhost:8080/website/resetdata` to load default mappings
3. Go to `http://localhost:8080/signin/generateadminuser` to generate the admin use
4. Go to `http://localhost:8080/website/cms`
5. Sign in as admin user
6. Reload the page
7. Go to `http://localhost:8080/website/cms/catchingrules`
8. Add the following catching rule:
    - SidebarTemplate for `/website/cms/catchingrules` (not Final)
9. Save and go to `http://localhost:8080/website/cms/surfaces`
10. Go back to `http://localhost:8080/website/cms/catchingrules`
11. Check Network tab

### Expected result
`http://localhost:8080/website/cms/catchingrules` XHR should contain operations only for changed paths.

### Actual result
`http://localhost:8080/website/cms/catchingrules` XHR contains `replace` for `""` path.

##### Involved apps' version

 - StarcounterApps/Website@32c0ba7cb35d93eeaac964ff0dc1bdd13199b3d3
 - StarcounterApps/SignIn@4bf03aac97c2eb411f1ba43bd59da3855eeb9230
 
##### Browsers affected

- [x] Chrome

### Screenshot
![image](https://cloud.githubusercontent.com/assets/1625378/23668270/a14e879e-0371-11e7-838a-3493aaa6687c.png)

**Comment by warpech** [comment]
This is related to #62 and should be worked on together.

**Comment by PatrykSzwer** [comment]
This issue is not reproducible anymore. After discussion with @un-tone we decided to close it.
