### ISSUE TITLE
Inifinte loop when no Catching Rule is default

### ISSUE THREAD

**Issue by joozek78** [StarcounterApps/Website#58]
### Steps to reproduce

1. Untick "final" checkbox beside all Catching Rules with empty URI
1. (Try to) load any page

### Expected result

Stuff loads and works. If no catching rule matches, then the page is loaded as-is

### Actual result

An infinite loop. Debug indicates it's somewhere inside here:

```
[External Code]	
WebsiteProvider.exe!WebsiteProvider.ContentHandlers.UpdateTemplateSections(string requestUri, Starcounter.Response response, WebsiteProvider.WebTemplatePage content, Simplified.Ring6.WebUrl url) Line 201	C#
WebsiteProvider.exe!WebsiteProvider.ContentHandlers.Register.AnonymousMethod__3_2(string requestUri) Line 102	C#
[External Code]	
WebsiteProvider.exe!WebsiteProvider.ContentHandlers.RegisterFilter.AnonymousMethod__6_1(Starcounter.Request request, Starcounter.Response response) Line 138	C#
[External Code]	
```

##### Starcounter version

2.3.0.5851

##### Involved apps' version

StarcounterApps/Website@0b1fa612cb1445d27f072a874b07b573fd9f2e16

**Comment by un-tone** [comment]
Created PR https://github.com/StarcounterApps/Website/pull/65.
Also I want to clarify, the application requires to have at least "final" or "catch-all" URI rule for all requests.

**Comment by joozek78** [comment]
It would be nice if it didn't required that, but that's actually quite easy to work around. More importantly, the application should tell the user about its requirements, not enter an infinite loop nor throw mysterious exception.

**Comment by warpech** [comment]
Once again I would start from taking inspiration from https://www.cloudflare.com/features-page-rules/must-use-page-rules/

> Only one Page Rule will trigger per URL, so it is helpful if you sort Page Rules in priority order, and make your URL patterns as specific as possible.

----

Let's translate it to our jargon:

1. Only one Catching Rule will trigger per Catch URI, so it is helpful if you sort Catching Rules in priority order, and make your URI patterns as specific as possible.

And let's add three more constrains:

2. A matched Catching Rule will cause a new run of the Catching Rules loop, using the Surface URI as the Catch URI in the new run
3. A matched Catching Rule can only be triggered once in the Catching Rules loop
4. The Catching Rules loop finishes when a matched Catching Rule is Final or if the URI does not matched any Catching Rule

@un-tone, @joozek78 WDYT? Is this powerful, naive, or somewhere in between?

**Comment by un-tone** [comment]
@joozek78 I eliminated that requirement

**Comment by un-tone** [comment]
Should be added tests covered this issue after merging https://github.com/StarcounterApps/Website/pull/71

**Comment by un-tone** [comment]
Tests are implemented.

**Comment by un-tone** [comment]
Closing as done
