### ISSUE TITLE
CompositionEditor only works correctly when started before Website

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Website#59]
### Steps to reproduce

1. Start Website `run.bat` (`develop` branch)
2. Start CompositionEditor `run.bat` (`develop` branch)
3. Go to `http://localhost:8080/website/cms`
4. Press CTRL+E

### Expected result

The Composion Editor panel should show up.

### Actual result

Nothing happens, the browser address bar gets focused.

This happens because Website middleware (`Application.Current.Use`) cancels CompositionEditor middleware. 

The editor works as expected if you run the apps in the following order:

1. CompositionEditor `run.bat`
2. Website `run.bat`
3. Press CTRL+E

**Comment by un-tone** [comment]
Created PR https://github.com/StarcounterApps/Website/pull/85

**Comment by un-tone** [comment]
Closing as done
