### ISSUE TITLE
Add tests to Website

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Website#60]
@un-tone, pls add Selenium tests to WebsiteProvider to test for the most common problems that were solved with the recent PRs.

The tests should be based on the structure of the testing framework used in https://github.com/StarcounterApps/KitchenSink/tree/develop/test/KitchenSink.Tests

Since Surfaces switch between many apps, I propose to create few helper apps for testing. The same approach was used in the past in Launcher: https://github.com/StarcounterApps/Launcher/tree/develop/test

**Comment by un-tone** [comment]
Created PR https://github.com/StarcounterApps/Website/pull/71

**Comment by un-tone** [comment]
Closing as done. For next fixes we agreed to always include tests (if it is applicable).
