### ISSUE TITLE
Synchronization problems for declared members in class that holds urihandlers.

### ISSUE THREAD

**Issue by chrhol** [StarcounterApps/Website#72]
Using members `CurrentResponse` and `CurrentTemplate` in class `ContentHandler` ([these lines](https://github.com/StarcounterApps/Website/blob/master/src/WebsiteProvider/Api/ContentHandlers.cs#L127-L128)) will not work since the urihandlers that reads and writes them can (and will) be called from more than one thread at the same time and these members are not threadsafe. 

This means that if there are two or more requests coming in at the same time the values will overwritten.

Some other way to solve this needs to be used. Perhaps capturing local variables is a better strategy?

### Steps to reproduce
Since it's a synchonization issue it's a bit more complicated and might not happen every time, but having more than one client sending requests at the same time will trigger this eventually. The effects might not be clear but the results when it happens is probably some messed up/incorrect responses.

**Comment by un-tone** [comment]
Fixed in https://github.com/StarcounterApps/Website/pull/65 (commits ae728c8 and 203d5a7).
Please review.

**Comment by un-tone** [comment]
Closing as done
