### ISSUE TITLE
Run the test project in TeamCity

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Website#73]
After PR https://github.com/StarcounterApps/Website/pull/71 is merged to develop, set up TeamCity to run the test project.

@KmaTTi89 is it possible to have a conditional config in every app in TC to run the test project if it exists? Then we can set up Website `develop` branch build to run the tests as well as the `master` branch build, even though `master` does not have the test project yet.

**Comment by KmaTTi89** [comment]
@warpech 
I can check that.
I will add testing build step to develop and master for Website project and disable it. I will enable it when test project will be in the code

**Comment by KmaTTi89** [comment]
Tests are running
