### ISSUE TITLE
Website Provider is detected by Avast antivirus as threat

### ISSUE THREAD

**Issue by tomalec** [StarcounterApps/Website#76]
### Steps to reproduce
1. execute run.bat with Avast antivirus running

### Expected result
App should run

### Actual result
App does not run as gets blocked.

##### Involved apps' version

https://github.com/StarcounterApps/Website/commit/5a955a365cbe4b288c1da68a8e280d835acb3dc7
 
##### Browsers affected
n/a

### Screenshot
![image](https://cloud.githubusercontent.com/assets/17435/24799269/a0371fe2-1b9a-11e7-9029-f74cefac2a5e.png)

**Comment by warpech** [comment]
I believe that there is nothing specific in `WebsiteProvider.exe`, this is a problem between Avast and Starcounter. Closing this, as it is tracked in https://github.com/Starcounter/level1/issues/1939
