### ISSUE TITLE
Why do I need Content app to run Website? WebSite provider is not mentioned.

### ISSUE THREAD

**Issue by tomalec** [StarcounterApps/Website#78]
### Steps to reproduce
1. Go to https://github.com/StarcounterApps/Website#sample-environment-setup-steps
2. Follow the steps

### Expected result
Minimal set of apps is running, you are able to experience the features of the app

### Actual result
Content seems to be not needed, WebSiteProvider and SignIn is needed.

##### Involved apps' version

https://github.com/StarcounterApps/Website/commit/5a955a365cbe4b288c1da68a8e280d835acb3dc7
 
##### Browsers affected

n/a

**Comment by warpech** [comment]
Taking this now

**Comment by warpech** [comment]
Fix in PR #90

**Comment by warpech** [comment]
Closing as done
