### ISSUE TITLE
Add info to the README on how to reset/generate data

### ISSUE THREAD

**Issue by tomalec** [StarcounterApps/Website#81]
### Steps to reproduce
1. open https://github.com/StarcounterApps/Website
2. try to find info how to reset default data

### Expected result
There is nice how to.

### Actual result
There is none.

##### Involved apps' version

https://github.com/StarcounterApps/Website/blob/162d13c9263ab8e47e0471c1759951445fe0f2c6/README.md
 
##### Browsers affected

n/a

**Comment by warpech** [comment]
Taking this now

**Comment by warpech** [comment]
Fix in PR #90

**Comment by warpech** [comment]
Closing as done
