### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by tomalec** [StarcounterApps/Website#89]
It seems we didn't release a version since Nov, and we made quite many changes.

I'd like to release new one to the warehouse. 
@warpech, @un-tone, @diliger Do you think we should bump something higher than PATCH?

**Comment by warpech** [comment]
Last release was Nov 30, 2015, so I would say *everything* has changed.

Please do the release, but the MAJOR number must be bumped.

**Comment by tomalec** [comment]
I have just released the Website and WebsiteProvider to the warehouse. However Website does not get stacked with old Website (http://warehouse.starcounter.com/warehouse/organizations/starcounter), as the namespaces does not match, should I completely remove the old one (http://warehouse.starcounter.com/warehouse/organizations/starcounter/softwares/website)? Hopefully to get nice URL for the new one (http://warehouse.starcounter.com/warehouse/organizations/starcounter/softwares/website1) - currently at `/website1`.

Or do we want to keep the old one for some time.

**Comment by tomalec** [comment]
Feel free to edit release notes https://github.com/StarcounterApps/Website/releases/tag/1.0.0 and add the changes you have made.

**Comment by warpech** [comment]
@andwah can you pls help with the above question regarding the Warehouse?

**Comment by andwah** [comment]
not sure if i can help with the question if we should keep the old WebSite app or not.  If we decide to keep it and we want the apps to be "stacked" then they need to have same `namespace` .  
We can update the namspace of the old version to be the same as the new one by changing the namspace in the config file and reupload it.

**Comment by warpech** [comment]
Thanks. Then I propose to just delete the old Website app in the warehouse. 

In broader context, there was a proposal to replace app namespaces with something else: https://github.com/Starcounter/Warehouse/issues/110

**Comment by tomalec** [comment]
Thanks for the comments :) I have just removed the old one, so now we have one and only http://warehouse.starcounter.com/warehouse/organizations/starcounter/softwares/website
