### ISSUE TITLE
Use GetHandlerForUri instead of current implementation of GetWildCardUrl

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Website#94]
In https://github.com/StarcounterApps/Website/pull/92#discussion_r113422681, a workaround was made for something that should be available as a helper method in Starcounter `Handle` class.

A new method `GetHandlerForUri` was requested in https://github.com/Starcounter/Home/issues/99 and it should be used in Website app when available.

**Comment by un-tone** [comment]
Closing as done
