### ISSUE TITLE
Signup icon is not visible with Latest SC RC (2.3.1.6410)

### ISSUE THREAD

**Issue by andwah** [StarcounterApps/Website#95]
Note, this work fine in RC 2.3.0.6350 but not in RC 2.3.1.6410

### Steps to reproduce

1. Install starcounter RC 2.3.1.6410
2. Install  Sign In v5.1.1 from app warehouse
2. Install  Website v1.0.0 from app warehouse
2. Install  WebsiteProvider v1.0.0 from app warehouse

### Expected result

Sigin in icon in upper right corner
![image](https://cloud.githubusercontent.com/assets/2656996/25798698/81c33c5c-33e2-11e7-89f9-031e421cfcca.png)

### Actual result

![image](https://cloud.githubusercontent.com/assets/2656996/25798712/8cd6f156-33e2-11e7-9266-081750ce24c6.png)

##### Involved apps' version

StarcounterPrefabs/Sign In v5.1.1 
StarcounterPrefabs/Website v1.0.0
StarcounterPrefabs/WebsiteProvider v1.0.0

**Comment by warpech** [comment]
This is not reproducible with `develop` branches. New versions will be released soon

**Comment by PatrykSzwer** [comment]
As far as I know It should be fixed right know. @andwah Please check and update.

**Comment by warpech** [comment]
Closing as not reproducible anymore
