### ISSUE TITLE
It is not possible to blend main response and pinned content

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Website#97]
Even though the main response and the pinned content are inside the same named blending point in the Website app, they are not blendable, because they show up in different `starcounter-includes`.

To make everything blendable, this view should have a single `starcounter-include` in it: https://github.com/StarcounterApps/Website/blob/develop/src/WebsiteProvider/wwwroot/WebsiteProvider/viewmodels/WebsiteSection.html#L6

Discuss this after PR #70 is merged.

**Comment by warpech** [comment]
I think that #97 should not be worked on right now, because it is a lot of effort and little benefit right now.

**Comment by un-tone** [comment]
Created PR https://github.com/StarcounterApps/Website/pull/161 for this issue

**Comment by un-tone** [comment]
Closing as done
