### ISSUE TITLE
Commit hook on removed pinned URL is missing

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Website#98]
Commit https://github.com/StarcounterApps/Website/commit/d9f05b6535c0c71afb30390a55d7f192939f8591 accidentally commented out the `BeforeDelete` hook on the class `WebMap`.

**Comment by un-tone** [comment]
Not accidentaly. I purposely left this commit https://github.com/StarcounterApps/Website/commit/c6e858bde2143f6bae8f89df88c9ebbddc9abf67

**Comment by un-tone** [comment]
There was 2 commits d9f05b6 and c6e858b. I've reverted only d9f05b6 because `BeforeDelete` commit hook works well

**Comment by un-tone** [comment]
Closing since there is not an issue
